default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['PG_HOST'] || localhost %>
  username: <%= ENV['PG_USERNAME'] || root %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  database: interest_places_ruby_development

test:
  <<: *default
  database: interest_places_ruby_test

production:
  <<: *default
  database: interest_places_ruby_production
  username: interest_places_ruby
  password: <%= ENV['INTEREST_PLACES_RUBY_DATABASE_PASSWORD'] %>
